version: "3"

services:
  # SERVER CONTAINER #
  server:
    build: ./server
    environment:
      PORT: ${SERVER_PORT}
      HOST: ${SERVER_HOST}
    expose:
      - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server/src:/usr/apps/portfolio/server/src
    command: npm run dev

  # CLIENT CONTAINER #
  client:
    build: ./client
    environment:
      PORT: ${REACT_APP_PORT} # PORT is the default name for the RN port env var
      SERVER_PORT: ${SERVER_PORT} # Used in packege.json to set proxy
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/usr/apps/portfolio/client/src
      - ./client/public:/usr/apps/portfolio/client/public
    links:
      - server
    command: npm run start
